# Config.yaml
# Setup parameters for calm-box
---
general:
    mode_one:
        timer_length: 3000
        start: [0, 255, 0]
        middle: [255, 255, 0]
        end: [255, 0, 0]
    mode_two:
        timer_length: 4800
        start: [0, 255, 0]
        middle: [0, 0, 255]
        end: [255, 0, 0]
led:
    pin: 18
    count: 60
    brightness: 65
    frequency: 800000
    inverted: false
    channel: 0
    dma: 10
button:
    primary: 17
    secondary: 27
